// kisskh.co backend — Asian Drama (KDrama / CDrama / JDrama / Anime / Hollywood).
//
// All metadata endpoints return clean JSON without auth. Stream extraction
// is gated by a signed `kkey` parameter generated by the site's own JS;
// that part is delegated to `KissKhExtractor` (headless webview).

import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

class KissKhService {
  static const String baseUrl = 'https://kisskh.co';
  static const String apiBase = '$baseUrl/api';
  static const String _userAgent =
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
      '(KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36';

  // ─── Cache (per-process, short-lived) ───────────────────────────
  static final Map<String, _CacheEntry> _httpCache = {};
  static const _cacheTtl = Duration(minutes: 10);

  // ─── HTTP helper ────────────────────────────────────────────────
  Future<String> _get(String url, {bool useCache = true}) async {
    if (useCache) {
      final cached = _httpCache[url];
      if (cached != null && DateTime.now().isBefore(cached.expires)) {
        return cached.body;
      }
    }
    final client = HttpClient()
      ..connectionTimeout = const Duration(seconds: 15);
    try {
      final req = await client.getUrl(Uri.parse(url));
      req.headers.set('User-Agent', _userAgent);
      req.headers.set('Accept', 'application/json,text/plain,*/*');
      req.headers.set('Referer', '$baseUrl/');
      req.followRedirects = true;
      final res = await req.close();
      final body = await res.transform(utf8.decoder).join();
      if (useCache) {
        _httpCache[url] = _CacheEntry(body, DateTime.now().add(_cacheTtl));
      }
      return body;
    } finally {
      client.close(force: true);
    }
  }

  List<KdramaCard> _parseCardList(String body) {
    try {
      final raw = jsonDecode(body);
      if (raw is! List) return const [];
      final out = <KdramaCard>[];
      for (final it in raw) {
        if (it is! Map) continue;
        final id = (it['id'] as num?)?.toInt();
        final title = (it['title'] ?? '').toString().trim();
        if (id == null || title.isEmpty) continue;
        out.add(KdramaCard(
          id: id,
          title: title,
          cover: (it['thumbnail'] ?? '').toString(),
          label: (it['label'] ?? '').toString().trim().isEmpty
              ? null
              : (it['label'] as String).trim(),
          episodesCount: (it['episodesCount'] as num?)?.toInt() ?? 0,
        ));
      }
      return out;
    } catch (e) {
      debugPrint('[KissKh] parse list failed: $e');
      return const [];
    }
  }

  // ─── Public API ────────────────────────────────────────────────
  Future<KdramaHomeFeed> getHome() async {
    final results = await Future.wait([
      _get('$apiBase/DramaList/Show'),
      _get('$apiBase/DramaList/LastUpdate?ispc=false'),
      _get('$apiBase/DramaList/MostView'),
      _get('$apiBase/DramaList/MostSearch?ispc=false'),
      _get('$apiBase/DramaList/TopRating?ispc=false'),
      _get('$apiBase/DramaList/Upcoming?ispc=false'),
      _get('$apiBase/DramaList/Animate?ispc=false'),
    ]);
    return KdramaHomeFeed(
      spotlight: _parseCardList(results[0]),
      latest: _parseCardList(results[1]),
      mostViewed: _parseCardList(results[2]),
      trending: _parseCardList(results[3]),
      topRated: _parseCardList(results[4]),
      upcoming: _parseCardList(results[5]),
      anime: _parseCardList(results[6]),
    );
  }

  Future<List<KdramaCard>> search(String query) async {
    final q = query.trim();
    if (q.isEmpty) return const [];
    final body = await _get(
      '$apiBase/DramaList/Search?q=${Uri.encodeQueryComponent(q)}&type=0',
      useCache: false,
    );
    return _parseCardList(body);
  }

  /// Browse the global catalog with filters. Backs the Explore screen.
  ///
  /// Filter codes (kisskh.ovh / kisskh.co Angular SPA):
  ///   type:    0=All, 1=TVSeries, 2=Movie, 3=Anime, 4=Hollywood
  ///   sub:     0=All, 1=English, 2=Khmer, 3=Indonesian, 4=Malay,
  ///            5=Thai, 6=Arabic
  ///   country: 0=All, 1=South Korea, 2=Chinese, 3=United States,
  ///            4=Thailand, 5=Philippine, 6=Japanese, 7=Hong Kong, 8=Taiwan
  ///   status:  0=All, 1=Ongoing, 2=Completed, 3=Upcoming
  ///   order:   1=Popular, 2=Last Update, 3=Release Date
  Future<KdramaExplorePage> explore({
    int page = 1,
    int type = 0,
    int sub = 0,
    int country = 0,
    int status = 0,
    int order = 1,
    int pageSize = 40,
  }) async {
    final url = '$apiBase/DramaList/List'
        '?page=$page&type=$type&sub=$sub&country=$country'
        '&status=$status&order=$order&pageSize=$pageSize';
    final body = await _get(url);
    try {
      final raw = jsonDecode(body);
      if (raw is! Map) {
        return const KdramaExplorePage(items: [], total: 0, page: 1);
      }
      final items = _parseCardList(jsonEncode(raw['data'] ?? const []));
      return KdramaExplorePage(
        items: items,
        total: (raw['totalCount'] as num?)?.toInt() ?? items.length,
        page: (raw['page'] as num?)?.toInt() ?? page,
        pageSize: (raw['pageSize'] as num?)?.toInt() ?? pageSize,
      );
    } catch (e) {
      debugPrint('[KissKh] explore parse failed: $e');
      return const KdramaExplorePage(items: [], total: 0, page: 1);
    }
  }

  Future<KdramaDetails> getDetails(int id) async {
    final body = await _get('$apiBase/DramaList/Drama/$id?isq=false');
    final raw = jsonDecode(body) as Map<String, dynamic>;
    final eps = <KdramaEpisode>[];
    for (final e in (raw['episodes'] as List? ?? const [])) {
      if (e is! Map) continue;
      final id = (e['id'] as num?)?.toInt();
      final n = (e['number'] as num?)?.toDouble();
      if (id == null || n == null) continue;
      eps.add(KdramaEpisode(
        id: id,
        number: n,
        sub: (e['sub'] as num?)?.toInt() ?? 0,
      ));
    }
    eps.sort((a, b) => a.number.compareTo(b.number));
    return KdramaDetails(
      id: (raw['id'] as num?)?.toInt() ?? id,
      title: (raw['title'] ?? '').toString().trim(),
      description: (raw['description'] ?? '').toString().trim(),
      cover: (raw['thumbnail'] ?? '').toString(),
      releaseDate: (raw['releaseDate'] ?? '').toString(),
      country: (raw['country'] ?? '').toString(),
      status: (raw['status'] ?? '').toString(),
      type: (raw['type'] ?? '').toString(),
      episodesCount:
          (raw['episodesCount'] as num?)?.toInt() ?? eps.length,
      label: (raw['label']?.toString().trim().isEmpty ?? true)
          ? null
          : raw['label'].toString().trim(),
      episodes: eps,
    );
  }

  /// Slug for URL building (title with spaces → dashes, lowercased).
  static String slugify(String title) {
    final s = title
        .toLowerCase()
        .replaceAll(RegExp(r"[''‘’`]"), '')
        .replaceAll(RegExp(r'[^a-z0-9]+'), '-')
        .replaceAll(RegExp(r'-+'), '-')
        .replaceAll(RegExp(r'^-|-$'), '');
    return s.isEmpty ? 'drama' : s;
  }

  /// Episode page URL — used as the WebView entry-point for the extractor.
  static String episodePageUrl({
    required int dramaId,
    required String title,
    required int episodeId,
    required double episodeNumber,
  }) {
    final slug = slugify(title);
    final epLabel = episodeNumber == episodeNumber.truncateToDouble()
        ? episodeNumber.toInt().toString()
        : episodeNumber.toString();
    return '$baseUrl/Drama/$slug/Episode-$epLabel'
        '?id=$dramaId&ep=$episodeId&page=0&pageSize=100';
  }

  // ─── Watch history (continue watching) ──────────────────────────
  static const String _historyKey = 'kisskh_history_v1';

  static final ValueNotifier<int> watchHistoryRevision = ValueNotifier<int>(0);

  Future<void> recordWatch({
    required KdramaCard drama,
    required double episodeNumber,
    required int totalEpisodes,
    Duration? position,
    Duration? duration,
  }) async {
    final p = await SharedPreferences.getInstance();
    final list = p.getStringList(_historyKey) ?? [];
    list.removeWhere((e) {
      try {
        return jsonDecode(e)['id'] == drama.id;
      } catch (_) {
        return true;
      }
    });
    list.insert(
      0,
      jsonEncode({
        'id': drama.id,
        'title': drama.title,
        'cover': drama.cover,
        'episodeNumber': episodeNumber,
        'totalEpisodes': totalEpisodes,
        'positionMs': position?.inMilliseconds ?? 0,
        'durationMs': duration?.inMilliseconds ?? 0,
        'updatedAt': DateTime.now().millisecondsSinceEpoch,
      }),
    );
    if (list.length > 50) list.removeRange(50, list.length);
    await p.setStringList(_historyKey, list);
    watchHistoryRevision.value++;
  }

  Future<List<Map<String, dynamic>>> getWatchHistory() async {
    final p = await SharedPreferences.getInstance();
    final list = p.getStringList(_historyKey) ?? [];
    final out = <Map<String, dynamic>>[];
    for (final raw in list) {
      try {
        out.add(jsonDecode(raw) as Map<String, dynamic>);
      } catch (_) {}
    }
    return out;
  }

  Future<Map<String, dynamic>?> getProgress(int id) async {
    final all = await getWatchHistory();
    for (final h in all) {
      if ((h['id'] as num?)?.toInt() == id) return h;
    }
    return null;
  }

  Future<void> removeFromHistory(int id) async {
    final p = await SharedPreferences.getInstance();
    final list = p.getStringList(_historyKey) ?? [];
    list.removeWhere((e) {
      try {
        return jsonDecode(e)['id'] == id;
      } catch (_) {
        return true;
      }
    });
    await p.setStringList(_historyKey, list);
    watchHistoryRevision.value++;
  }
}

class _CacheEntry {
  final String body;
  final DateTime expires;
  _CacheEntry(this.body, this.expires);
}

// ════════════════════════════════════════════════════════════════════
//  Models
// ════════════════════════════════════════════════════════════════════

class KdramaCard {
  final int id;
  final String title;
  final String cover;
  final String? label;
  final int episodesCount;

  const KdramaCard({
    required this.id,
    required this.title,
    required this.cover,
    this.label,
    this.episodesCount = 0,
  });
}

class KdramaHomeFeed {
  final List<KdramaCard> spotlight;
  final List<KdramaCard> latest;
  final List<KdramaCard> mostViewed;
  final List<KdramaCard> trending;
  final List<KdramaCard> topRated;
  final List<KdramaCard> upcoming;
  final List<KdramaCard> anime;

  const KdramaHomeFeed({
    this.spotlight = const [],
    this.latest = const [],
    this.mostViewed = const [],
    this.trending = const [],
    this.topRated = const [],
    this.upcoming = const [],
    this.anime = const [],
  });
}

class KdramaDetails {
  final int id;
  final String title;
  final String description;
  final String cover;
  final String releaseDate;
  final String country;
  final String status;
  final String type;
  final int episodesCount;
  final String? label;
  final List<KdramaEpisode> episodes;

  const KdramaDetails({
    required this.id,
    required this.title,
    required this.description,
    required this.cover,
    required this.releaseDate,
    required this.country,
    required this.status,
    required this.type,
    required this.episodesCount,
    this.label,
    this.episodes = const [],
  });

  String? get year {
    if (releaseDate.length >= 4) {
      final y = releaseDate.substring(0, 4);
      if (RegExp(r'^\d{4}$').hasMatch(y)) return y;
    }
    return null;
  }

  KdramaCard toCard() => KdramaCard(
        id: id,
        title: title,
        cover: cover,
        label: label,
        episodesCount: episodesCount,
      );
}

class KdramaEpisode {
  final int id;
  final double number;
  final int sub;

  const KdramaEpisode({
    required this.id,
    required this.number,
    this.sub = 0,
  });

  String get displayNumber {
    if (number == number.truncateToDouble()) return number.toInt().toString();
    return number.toString();
  }
}

/// Single page of the `/DramaList/List` Explore endpoint.
class KdramaExplorePage {
  final List<KdramaCard> items;
  final int total;
  final int page;
  final int pageSize;
  const KdramaExplorePage({
    required this.items,
    required this.total,
    required this.page,
    this.pageSize = 40,
  });

  bool get hasMore => page * pageSize < total;
}

/// Static lookup tables for the Explore filter chips. Order matches the
/// integer codes consumed by `KissKhService.explore(...)`.
class KissKhExploreFilters {
  static const List<String> types = [
    'All', 'TV Series', 'Movie', 'Anime', 'Hollywood',
  ];
  static const List<String> subtitles = [
    'All', 'English', 'Khmer', 'Indonesian', 'Malay', 'Thai', 'Arabic',
  ];
  static const List<String> countries = [
    'All', 'South Korea', 'Chinese', 'United States', 'Thailand',
    'Philippine', 'Japanese', 'Hong Kong', 'Taiwan',
  ];
  static const List<String> statuses = [
    'All', 'Ongoing', 'Completed', 'Upcoming',
  ];
  static const List<String> orders = [
    // index 0 unused — the API uses 1-based ordering codes.
    '', 'Popular', 'Last Update', 'Release Date',
  ];
}
